name: ai_strike
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+1 
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  uuid: ^3.0.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

